# define a list of syndrome strings that can identify sets of individuals with
# shared suspected-syndromes

# note when we search for these syndromes, those that have dashes may have spaces
# instead, or vice versa, or dashes and spaces combined, or no gap between the
# words e.g. DiGeorge, Di-George, Di George, Di -George.
SYNDROMES = c("22q",
    "3m",
    "9q34",
    "17q21",
    "aars[k|h]+o(r)*g",
    "achondroplasia",
    "acrodysostosis",
    "aicardi-goutiere",
    "a(l)+an he(a)*rndon dudley",
    "alagille",
    "albright",
    "alpers",
    "alstrom",
    "ang[el|le]+(r)*man",
    "arx",
    "atr-x",
    "arterial tortuosity",
    "ataxia telangectasia",
    "autism|asd|autistic",
    "bardet-b[ei|ie]+dl",
    "bbs",
    "beal",
    "beckw[or|i]+th|beckw[i|or]+th-wi[e]*[i]*de[r]*man",
    "bilateral frontoparietal polymicrogyria",
    "blepharophimosis",
    "borjeson-forssman-lehman",
    "bpes",
    "brachytelephalangic",
    "bran(c)*hio-oto-renal",
    "cardiofaci[o|al]+cutaneous",
    "carey fineman ziter",
    "charcot marie tooth",
    "charge",
    "c[il|li]+iopathy",
    "cerebral palsy",
    "coach",
    "cockayn[e|c]+",
    "coffin-lowry",
    "coffin-siris",
    "cohen",
    "congenital central hypoventilation",
    "congenital leptin",
    "congenital myastheni[c|a]+",
    "congenital myopathy",
    "connective-tissue-disorder",
    "[cornelia]* de lange",
    "costello",
    "cowden",
    "craniosynostosis",
    "crisponi",
    "crouzon",
    "currarino",
    "di ge[o]*rge",
    "distal arthrogryposis",
    "dopa responsive",
    "dravet",
    "duane",
    "dubowitz",
    "ectodermal dysplasia",
    "east syndrome",
    "ehlers-danlos",
    "epileptic encephalopathy",
    "fabrys",
    "fanco(n)+i",
    "feingold",
    "f[o]*etal alcohol",
    "fi(l)+i(p)+i",
    "floating harbo(u)*r",
    "fr[ag|ga]+il(k)*e x",
    "freeman sheldon",
    "fg syndrome",
    "gauchers",
    "gillespie",
    "glut[1|l]+ deficiency",
    "goldenha[a]*r",
    "gomez lopez hernandes",
    "gordon",
    "gorlin",
    "griegs",
    "hand-foot-genital",
    "holoprosencephaly",
    "holt-oram",
    "joubert",
    "kallman",
    "k[au]buki",
    "kbg",
    "kleefstra",
    "kneist",
    "larsen",
    "leigh",
    "lennox-gastaut",
    "lipodystroph[y|ies]+",
    "lissencephaly",
    "loeys dietz",
    "lujan",
    "marfan",
    "masa(\b|$)+",
    "mecp2",
    "millier-dieker",
    "mitochond[r]*ial",
    "mow(a)+(t)+-wilson",
    "moebius",
    "mosaic tri",
    "mosaicism",
    "mucolipidosis",
    "muscular dystrophy",
    "myhre",
    "myotonic dystrophy",
    "myoclonus dystonia",
    "nf1",
    "nic[o|h]+laides-baraitser",
    "nijmegen breakage",
    "noonan",
    "no(r)+ies",
    "ober[k]*laid-danks",
    "oculo-dental-digital",
    "oculofaciocardiodental",
    "o[hd|dh]+o",
    "o[h]*t[a|o]+hara|ohtara",
    "okihiro",
    "opitz (g)*",
    "or[al|o]+-facial-digital",
    "osteogenesis",
    "overgrowth",
    "pallister killian",
    "pallister hall",
    "peho",
    "p[a|e][r]*liz[a]*eus-merz-bacher",
    "phaces",
    "pierre robin",
    "pit[t]*-hopkin",
    "poland",
    "pontocerebellar",
    "[prada|prader]-willi",
    "primary microcephaly",
    "proteus",
    "pten",
    "pws",
    "rett",
    "robinow",
    "rothmund thomson",
    "rub[e|i]+nst[ei|ie]+n-[r|t]+aybi",
    "russe(l)+-s[il|li]+[ve|ev]+r|silver-russell",
    "slo|smith-le[m]*[l]*i[l]*-op[it|ti]+z",
    "sma(\b|$)",
    "smith-mage(n)+[i|e]+s",
    "soto[s]*",
    "schinzel g[i|l]+(e)*d[i|e]+on",
    "shprintzen|s[c]*hprintzen-goldber[g|y]+|goldberg-shpri[n]*tzen",
    "sensenbrenner",
    "simpso[m|n]+-golabi-behmel",
    "septo-optic dysp[al|la]+sia",
    "spinocerebellar",
    "stickler",
    "tre[a|n]cher collins",
    "town[e]*s-brock",
    "trichor[h]*inophalangeal",
    "turner",
    "UPD [14]*",
    "usher",
    "vacter[a]*l",
    "vater",
    "velo-cardi[o|al]+-fac[ial|e]+|vcf",
    "waardenburg",
    "walker-warburg",
    "weaver",
    "west",
    "wiede[r]*mann-steiner",
    "wil(l)+iam[s]*",
    "wolfmans",
    "worster[-|_| ]*drought",
    "x-inactivation",
    "x-linked-mental-retardation")
