# define a list of syndrome strings that can identify sets of individuals with
# shared suspected-syndromes

# note when we search for these syndromes, those that have dashes may have spaces
# instead, or vice versa, or dashes and spaces combined, or not gap between the
# words.
SYNDROMES = c("22q11",
    "3m",
    "9q34",
    "17q21",
    "aars[k|h]+o(r)*g",
    "achondroplasia",
    "acrodysostosis",
    "aicardi-goutiere",
    "a(l)+an herndon dudley",
    "alagille",
    "albright",
    "alstrom",
    "ang[el|le]+man",
    "arx",
    "atr-x",
    "arterial tortuosity",
    "autism|asd|autistic",
    "bardet-b[ei|ie]+dl",
    "bbs",
    "beals",
    "beckw[i|or]+th-wi[e]*[i]*de[r]*man",
    "bilateral frontoparietal polymicrogyria",
    "blepharophimosis",
    "borjeson-forssman-lehman",
    "brachytelephalangic",
    "bran(c)*hio-oto-renal",
    "cardiofaci[o|al]+cutaneous",
    "carey fineman ziter",
    "charcot marie tooth",
    "charge",
    "ciliopathy",
    "cockayn[e|c]+",
    "coffin-lowry",
    "coffin-siris",
    "cohen",
    "congenital central hypoventilation",
    "congenital leptin",
    "congenital myastheni[c|a]+",
    "congenital myopathy",
    "connective-tissue-disorder",
    "[cornelia]* de lange",
    "costello",
    "cowden",
    "craniosynostosis",
    "crisponi",
    "crouzon",
    "currarino",
    "di ge[o]*rge",
    "distal arthrogryposis",
    "dopa responsive",
    "dravet",
    "duane",
    "dubowitz",
    "east syndrome",
    "ehlers-danlos",
    "epileptic encephalopathy",
    "fanco(n)+i",
    "feingold",
    "f[o]*etal alcohol",
    "fi(l)+i(p)+i",
    "floating harbo(u)*r",
    "fragile x",
    "freeman sheldon",
    "fg syndrome",
    "gillespie",
    "glut1 deficiency",
    "goldenha[a]*r",
    "gomez lopez hernandes",
    "gordon",
    "gorlin",
    "hand-foot-genital",
    "holoprosencephaly",
    "holt-oram",
    "joubert",
    "kallman",
    "k[au]buki",
    "kbg",
    "kleefstra",
    "kneist",
    "larsen",
    "leigh",
    "lennox-gastaut",
    "lipodystroph[y|ies]+",
    "lissencephaly",
    "loeys dietz",
    "lujan",
    "marfan",
    "masa(\b|$)+",
    "mow(a)+(t)+-wilson",
    "mitochond[r]*ial",
    "moebius",
    "mosaic tri",
    "mosaicism",
    "myhre",
    "myotonic dystrophy",
    "myoclonus dystonia",
    "nicolaides-baraitser",
    "nijmegen breakage",
    "noonan",
    "norries",
    "ober[k]*laid-danks",
    "oculo-dental-digital",
    "oculofaciocardiodental",
    "ohdo",
    "o[h]*t[a|o]+hara|ohtara",
    "okihiro",
    "opitz g",
    "or[al|o]+-facial-digital",
    "osteogenesis",
    "pallister killian",
    "pallister hall",
    "peho",
    "p[a|e][r]*liz[a]*eus-merz-bacher",
    "phaces",
    "pierre robin",
    "pit[t]*-hopkin",
    "poland",
    "pontocerebellar",
    "[prada|prader]-willi",
    "primary microcephaly",
    "proteus",
    "pten",
    "pws",
    "rett",
    "robinow",
    "rothmund thomson",
    "rub[e|i]+nst[ei|ie]+n-[r|t]+aybi",
    "russe(l)+-s[il|li]+[ve|ev]+r|silver-russell",
    "slo|smith-le[m]*[l]*i[l]*-opitz",
    "sma(\b|$)",
    "smith-magen[i|e]+s",
    "soto[s]*",
    "schinzel g[i|l]+edion",
    "s[c]*hprintzen-goldberg|goldberg-shpri[n]*tzen",
    "sensenbrenner",
    "simpso[m|n]+-golabi-behmel",
    "septo-optic dysp[al|la]+sia",
    "spinocerebellar",
    "stickler",
    "tre[a|n]cher collins",
    "town[e]*s-brock",
    "trichor[h]*inophalangeal",
    "turner",
    "usher",
    "vacter[a]*l",
    "vater",
    "waardenburg",
    "walker-warburg",
    "weaver",
    "west",
    "wiede[r]*mann-steiner",
    "william[s]*",
    "worster[-|_| ]*drought",
    "x-inactivation",
    "x-linked-mental-retardation")
