# define a list of syndrome strings that can identify sets of individuals with
# shared suspected-syndromes

# note when we search for these syndromes, those that have dashes may have spaces
# instead, or vice versa, or dashes and spaces combined, or no gap between the
# words e.g. DiGeorge, Di-George, Di George, Di -George.
SYNDROMES = data.frame(matrix(c("22q", "22q deletion",
    "3m", "3-M syndrome",
    "17q21", "17q21 deletion",
    "aars[k|h]+o(r)*g", "Aarskog syndrome",
    "achondroplasia", "Achondroplasia",
    "acrodysostosis", "Acrodysostosis",
    "aicardi-goutiere", "Aicardi-Goutiere",
    "a(l)+an he(a)*rndon dudley", "Allan-Herndon-Dudley syndrome",
    "alagille", "Alagille syndrome",
    "albright", "McCune-Albright syndrome",
    "alpers", "Alpers' disease",
    "alstrom", "Alström syndrome",
    "ang[el|le]+(r)*man", "Angelman syndrome",
    "arx", "ARX",
    "atr-x", "ATR-X",
    "arterial tortuosity", "Arterial tortuosity",
    "ataxia telangectasia", "Ataxia telengectasia",
    "autism|asd|autistic", "Austism spectrum disorder",
    "bardet-b[ei|ie]+dl|bbs", "Bardet-Beidl syndrome",
    "beal", "Beals syndrome",
    "beckw[or|i]+th|beckw[i|or]+th-wi[e]*[i]*de[r]*man", "Beckwith-Weidemann syndrome",
    "bilateral frontoparietal polymicrogyria", "Bilateral frontoparietal polymicrogyria",
    "blepharophimosis", "Blepharophimosis",
    "borjeson-forssman-lehman", "Börjeson-Forssman-Lehmann syndrome",
    "bpes", "BPES",
    "brachytelephalangic", "Brachytelephalangic",
    "bran(c)*hio-oto-renal", "Branchio-oto-renal syndrome",
    "cardiofaci[o|al]+cutaneous", "Cardiofaciocutaneous",
    "carey fineman ziter", "Carey-Fineman-Ziter syndrome",
    "charcot marie tooth", "Charcot-Marie-Tooth disease",
    "charge", "CHARGE syndrome",
    "c[il|li]+iopathy", "Ciliopathy",
    "cerebral palsy", "Cerebral palsy",
    "coach", "COACH syndrome",
    "cockayn[e|c]+", "Cockayne syndrome",
    "coffin-lowry", "Coffin-Lowry syndrome",
    "coffin-siris", "Coffin-Siris syndrome",
    "cohen", "Cohen syndrome",
    "congenital central hypoventilation", "Congenital central hypoventilation",
    "congenital leptin", "Congenital leptin",
    "congenital myastheni[c|a]+", "Congenital myasthenia",
    "congenital myopathy", "Congenital myopathy",
    "connective-tissue-disorder", "Connective-Tissue disorder",
    "[cornelia]* de lange", "Cornelia De Lange syndrome",
    "costello", "Costello syndrome",
    "cowden", "Cowden syndrome",
    "craniosynostosis", "Craniosynostosis",
    "crisponi", "Crisponi syndrome",
    "crouzon", "Crouzon syndrome",
    "currarino", "Currarino syndrome",
    "di ge[o]*rge", "DiGeorge syndrome",
    "distal arthrogryposis", "Distal arthrogryposis",
    "dopa responsive", "Dopa-responsive dystonia",
    "dravet", "Dravet syndrome",
    "duane", "Duane syndrome",
    "dubowitz", "Dubowitz syndrome",
    "ectodermal dysplasia", "Ectodermal dysplasia",
    "east syndrome", "East syndrome",
    "ehlers-danlos", "Ehlers-Danlos syndrome",
    "epileptic encephalopathy", "Epileptic encephalopathy",
    "fabrys", "Fabrys disease",
    "fanco(n)+i", "Fanconi anemia",
    "feingold", "Feingold syndrome",
    "f[o]*etal alcohol", "Fetal alcohol syndrome",
    "fi(l)+i(p)+i", "Filippi syndrome",
    "floating harbo(u)*r", "Floating-Harbor syndrome",
    "fr[ag|ga]+il(k)*e x", "Fragile-X syndrome",
    "freeman sheldon", "Freeman-Sheldon syndrome",
    "fg syndrome|opitz-kaveggia", "FG syndrome",
    "gauchers", "Gaucher disease",
    "gillespie", "Gillespie syndrome",
    "glut[1|l]+ deficiency", "GLUT1 deficiency",
    "goldenha[a]*r", "Goldenhar syndrome",
    "gomez lopez hernandes", "Gomez-Lopez-Hernandes syndrome",
    "gordon", "Gordon syndrome",
    "gorlin", "Gorlin syndrome",
    "griegs", "Greig cephalopolysyndactyly syndrome",
    "hand-foot-genital", "Hand-foot-genital syndrome",
    "holoprosencephaly", "Holoprosencephaly",
    "holt-oram", "Holt-Oram syndrome",
    "joubert", "Joubert syndrome",
    "kallman", "Kallman syndrome",
    "k[au]buki", "Kabuki syndrome",
    "kbg", "KBG syndrome",
    "kleefstra|9q34", "Kleefstra syndrome",
    "kneist", "Kniest dysplasia",
    "larsen", "Larsen syndrome",
    "leigh", "Leigh disease",
    "lennox-gastaut",  "Lennox-Gastaut syndrome",
    "lipodystroph[y|ies]+", "Lipodystrophy",
    "lissencephaly", "Lissencephaly",
    "loeys dietz", "Loeys-Dietz syndrome",
    "lujan", "Lujan syndrome",
    "marfan", "Marfan syndrome",
    "masa(\b|$)+", "MASA syndrome",
    "miller-dieker", "Miller-Dieker syndrome",
    "mitochond[r]*ial", "Mitochondrial disorder",
    "mow(a)+(t)+-wilson", "Mowat-Wilson syndrome",
    "moebius", "Möbius syndrome",
    "mosaic tri", "Mosaic trisomy chr21",
    "mosaicism", "Mosaicism",
    "mucolipidosis", "Mucolipidosis",
    "muscular dystrophy", "Muscular dystrophy",
    "myhre", "Myhre syndrome",
    "myotonic dystrophy", "Myotonic dystrophy",
    "myoclonus dystonia", "Myoclonus dystonia",
    "nf1", "Neurofibromatosis type 1",
    "nic[o|h]+laides-baraitser", "Nicolaides-Baraitser syndrome",
    "nijmegen breakage", "Nijmegen breakage syndrome",
    "noonan", "Noonan syndrome",
    "no(r)+ies", "Norrie disease",
    "ober[k]*laid-danks", "Oberklaid-Danks syndrome",
    "oculo-dental-digital", "Oculodentodigital dysplasia",
    "oculofaciocardiodental", "Oculofaciocardiodental syndrome",
    "o[hd|dh]+o", "Ohdo syndrome",
    "o[h]*t[a|o]+hara|ohtara", "Ohtahara syndrome",
    "okihiro", "Okihiro syndrome",
    "opitz g", "Opitz G/BBB syndrome",
    "or[al|o]+-facial-digital", "Oral-facial-dental syndrome",
    "osteogenesis", "Osteogenesis",
    "overgrowth", "Overgrowth",
    "pallister killian", "Pallister-Killian syndrome",
    "pallister hall", "Pallister-Hall syndrome",
    "peho", "PEHO syndrome",
    "p[a|e][r]*liz[a]*eus-merz-bacher", "Pelizaeus-Merzbacher disease",
    "phaces", "PHACES syndrome",
    "pierre robin", "Pierre Robin syndrome",
    "pit[t]*-hopkin", "Pitt-Hopkins syndrome",
    "poland", "Poland syndrome",
    "pontocerebellar", "Pontocerebellar hypoplasia",
    "[prada|prader]-willi|pws", "Prader-Willi syndrome",
    "primary microcephaly", "Primary microcephaly",
    "proteus", "Proteus syndrome",
    "pten", "PTEN",
    "rett|mecp2", "Rett syndrome",
    "robinow", "Robinow syndrome",
    "rothmund thomson", "Rothmund-Thomson syndrome",
    "rub[e|i]+nst[ei|ie]+n-[r|t]+aybi", "Rubinstein-Taybi syndrome",
    "russe(l)+-s[il|li]+[ve|ev]+r|silver-russell", "Silver-Russell syndrome",
    "slo|smith-le[m]*[l]*i[l]*-op[it|ti]+z", "Smith-Lemli-Opitz syndrome",
    "sma(\b|$)", "SMA",
    "smith-mage(n)+[i|e]+s", "Smith-Magenis syndrome",
    "soto[s]*", "Sotos syndrome",
    "schinzel g[i|l]+(e)*d[i|e]+on", "Schinzel-Giedeon syndrome",
    "shprintzen|s[c]*hprintzen-goldber[g|y]+|goldberg-shpri[n]*tzen", "Shprintzen-Goldberg syndrome",
    "sensenbrenner", "Sensenbrenner syndrome",
    "simpso[m|n]+-golabi-behmel", "Simpson-Golabi-Behmel syndrome",
    "septo-optic dysp[al|la]+sia", "Septo-optic dysplasia",
    "spinocerebellar", "Spinocerebellar ataxia",
    "stickler", "Stickler syndrome",
    "tre[a|n]cher collins", "Treacher Collins syndrome",
    "town[e]*s-brock", "Townes-Brock syndrome",
    "trichor[h]*inophalangeal", "Trichorhinophalangeal",
    "turner", "Turner syndrome",
    "upd [14]*", "UPD-14 syndrome",
    "usher", "Usher syndrome",
    "vacter[a]*l|vater", "VACTERAL association",
    "velo-cardi[o|al]+-fac[ial|e]+|vcf", "Velocardiofacial syndrome",
    "waardenburg", "Waardenburg syndrome",
    "walker-warburg", "Walker-Warburg syndrome",
    "weaver", "Weaver syndrome",
    "west", "West syndrome",
    "wiede[r]*mann-steiner", "Wiedemann-Steiner syndrome",
    "wil(l)+iam[s]*", "Williams syndrome",
    "wolfmans", "Wolfman syndrome",
    "worster[-|_| ]*drought", "Worster-Drought syndrome",
    "x-inactivation", "X-inactivation",
    "x-linked-mental-retardation", "X-linked mental retardation"),
    ncol=2, byrow=TRUE))
names(SYNDROMES) = c("regex", "name")

save(SYNDROMES, file="data/syndromes_list.rda", compress="xz")
